# Generated by Django 5.0.3 on 2024-03-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bulim_id', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ish_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ish_id', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mahsulot_id', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('xato_id', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='xodimmahsulot',
            name='mahsulot',
        ),
        migrations.RemoveField(
            model_name='xodimmahsulot',
            name='xodim',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='familiya',
        ),
        migrations.RemoveField(
            model_name='xodim',
            name='ism',
        ),
        migrations.AddField(
            model_name='xodim',
            name='first_name',
            field=models.CharField(default=True, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodim',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Null', 'Null')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='xodim',
            name='id_raqam',
            field=models.CharField(default=True, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodim',
            name='last_name',
            field=models.CharField(default=True, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodim',
            name='phone',
            field=models.CharField(default=True, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodim',
            name='bulim',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolim', to='firma.bolim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bolim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firma.ish_turi'),
        ),
        migrations.AddField(
            model_name='xodim',
            name='ish_turi',
            field=models.ManyToManyField(related_name='ish_turi', to='firma.ish_turi'),
        ),
        migrations.CreateModel(
            name='Hisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('xato_soni', models.PositiveIntegerField(default=0)),
                ('butun_soni', models.PositiveIntegerField(default=0)),
                ('ish_vaqti', models.PositiveIntegerField(null=True)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xodim', to='firma.xodim')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maxsulot', to='firma.maxsulot')),
                ('xato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='firma.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='Mahsulot',
        ),
        migrations.DeleteModel(
            name='XodimMahsulot',
        ),
    ]
